# -*- coding: utf-8 -*-
"""Health Care Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pm4WdNmvTJ1ELE2MnGE40QObwYOaLUXy
"""

!pip install faker

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from faker import Faker
import random

fake = Faker()
Faker.seed(42)

data = []

for i in range(10000):
    gender = random.choice(["Male", "Female"])

    patient = {
        "Patient_ID": i+1,
        "Name": fake.name(),
        "Age": random.randint(20, 80),
        "Gender": gender,
        "Blood_Pressure": random.randint(80, 180),
        "Sugar_Level": random.randint(70, 200),
        "Cholesterol": random.randint(150, 300),
        "Heart_Rate": random.randint(60, 120)
    }

    data.append(patient)

df = pd.DataFrame(data)
df.head()

print(df.isnull().sum())
df["Gender"] = df["Gender"].map({"Male": 0, "Female": 1})
df.info()

def risk_level(row):
    if (row["Blood_Pressure"] > 140 or
        row["Sugar_Level"] > 160 or
        row["Cholesterol"] > 240):
        return "High"
    elif (row["Blood_Pressure"] > 120 or
          row["Sugar_Level"] > 120 or
          row["Cholesterol"] > 200):
        return "Medium"
    else:
        return "Low"

df["Risk_Level"] = df.apply(risk_level, axis=1)

df.head()

plt.hist(df["Age"], bins=20)
plt.title("Age Distribution")
plt.show()

plt.scatter(df["Age"], df["Blood_Pressure"])
plt.xlabel("Age")
plt.ylabel("Blood Pressure")
plt.title("Age vs Blood Pressure")
plt.show()

df["Risk_Level"].value_counts().plot(kind="bar")
plt.title("Risk Level Count")
plt.show()

print(df.groupby("Gender")["Blood_Pressure"].mean())
df["Age_Group"] = pd.cut(df["Age"], bins=[20,30,40,50,60,70,80])
print(df.groupby("Age_Group")["Risk_Level"].value_counts())

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

X = df[["Age", "Gender", "Blood_Pressure", "Sugar_Level", "Cholesterol", "Heart_Rate"]]
y = df["Risk_Level"]

le = LabelEncoder()
y = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

new_patient = pd.DataFrame({
    "Age": [60],
    "Gender": [1],
    "Blood_Pressure": [150],
    "Sugar_Level": [170],
    "Cholesterol": [260],
    "Heart_Rate": [85]
})

pred = model.predict(new_patient)
print("Predicted Risk:", le.inverse_transform(pred)[0])

df.to_csv("faker_healthcare_data.csv", index=False)